import { useApp } from "../App";
import CodeViewer from "../components/CodeViewer";

export default function Output() {
  const { migrateResult, targetLang, setRoute } = useApp();

  return (
    <div style={styles.page}>
      <div style={styles.header}>
        <div>
          <div style={styles.eyebrow}>Step 3 of 3</div>
          <h1 style={styles.title}>Migration Output</h1>
          <p style={styles.sub}>
            Translated files generated by the local LLM, with parity validation
            and a confidence score based on dependency coverage.
          </p>
        </div>
        {migrateResult && (
          <div style={styles.metaRow}>
            <MetaBadge
              value={migrateResult.parity}
              label="Parity"
              color={migrateResult.parity === "PASS" ? "#166534" : migrateResult.parity === "SKIP" ? "#854d0e" : "#991b1b"}
              bg={migrateResult.parity === "PASS" ? "#dcfce7" : migrateResult.parity === "SKIP" ? "#fef9c3" : "#fee2e2"}
              border={migrateResult.parity === "PASS" ? "#86efac" : migrateResult.parity === "SKIP" ? "#fde047" : "#fca5a5"}
            />
            <MetaBadge
              value={`${Math.round(migrateResult.confidence_score * 100)}%`}
              label="Confidence"
              color="#92400e"
              bg="#fff7ed"
              border="#fed7aa"
            />
            <MetaBadge
              value={`${migrateResult.files_migrated}`}
              label="Files"
              color="#1e3a5f"
              bg="#eff6ff"
              border="#bfdbfe"
            />
          </div>
        )}
      </div>

      {!migrateResult && (
        <div style={styles.empty}>
          <div style={styles.emptyIcon}>◈</div>
          <div style={styles.emptyTitle}>No output yet</div>
          <div style={styles.emptySub}>Run Migrate from the home page to generate translated code.</div>
          <button onClick={() => setRoute("home")} style={styles.emptyBtn}>← Go to Home</button>
        </div>
      )}

      {migrateResult && (
        <div style={styles.viewerCard}>
          <CodeViewer
            files={migrateResult.files || []}
            parity={migrateResult.parity}
            confidenceScore={migrateResult.confidence_score}
            executionTimeMs={migrateResult.execution_time_ms}
            language={targetLang}
          />
        </div>
      )}

      {migrateResult && (
        <div style={styles.footer}>
          <button onClick={() => setRoute("graph")} style={styles.btnSecondary}>← View Graph</button>
          <button onClick={() => setRoute("home")} style={styles.btnPrimary}>New Migration →</button>
        </div>
      )}
    </div>
  );
}

function MetaBadge({ value, label, color, bg, border }) {
  return (
    <div style={{ ...styles.metaBadge, background: bg, border: `1px solid ${border}` }}>
      <span style={{ ...styles.metaBadgeVal, color }}>{value}</span>
      <span style={styles.metaBadgeLabel}>{label}</span>
    </div>
  );
}

const styles = {
  page: { padding: "60px 64px", animation: "fadeUp 0.4s ease" },
  header: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 24, marginBottom: 40, flexWrap: "wrap" },
  eyebrow: { fontSize: 12, fontWeight: 600, letterSpacing: "0.12em", color: "#b5692a", textTransform: "uppercase", marginBottom: 10, fontFamily: "'DM Mono', monospace" },
  title: { fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 40, color: "#2a2420", marginBottom: 14, lineHeight: 1.1 },
  sub: { fontSize: 15, color: "#6b5f54", lineHeight: 1.7, maxWidth: 480, fontWeight: 300 },
  metaRow: { display: "flex", gap: 12, flexWrap: "wrap", alignItems: "flex-start" },
  metaBadge: { borderRadius: 12, padding: "16px 20px", textAlign: "center", minWidth: 90 },
  metaBadgeVal: { display: "block", fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 24, lineHeight: 1, marginBottom: 4 },
  metaBadgeLabel: { fontSize: 11, color: "#9a8f82", fontWeight: 500, letterSpacing: "0.06em" },
  viewerCard: { background: "#fff", border: "1px solid #e0d8cc", borderRadius: 16, overflow: "hidden", boxShadow: "0 4px 24px rgba(42,36,32,0.07)", marginBottom: 32 },
  empty: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 14, padding: "80px 0", textAlign: "center" },
  emptyIcon: { fontSize: 48, color: "#c4b99a" },
  emptyTitle: { fontFamily: "'Playfair Display', serif", fontSize: 24, color: "#2a2420", fontWeight: 600 },
  emptySub: { fontSize: 15, color: "#9a8f82", fontWeight: 300 },
  emptyBtn: { marginTop: 8, padding: "10px 22px", borderRadius: 10, border: "1.5px solid #c4b99a", background: "transparent", color: "#6b5f54", fontSize: 14, fontWeight: 600, cursor: "pointer", fontFamily: "'DM Sans', sans-serif" },
  footer: { display: "flex", gap: 12 },
  btnSecondary: { padding: "12px 22px", borderRadius: 10, border: "1.5px solid #c4b99a", background: "transparent", color: "#6b5f54", fontSize: 14, fontWeight: 600, cursor: "pointer", fontFamily: "'DM Sans', sans-serif" },
  btnPrimary: { padding: "12px 26px", borderRadius: 10, border: "none", background: "#2a2420", color: "#f5f0e8", fontSize: 14, fontWeight: 600, cursor: "pointer", fontFamily: "'DM Sans', sans-serif" },
};